//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarRailTool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarRailTool.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Could not convert {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create process. 的本地化字符串。
        /// </summary>
        internal static string CreateProcessFailed {
            get {
                return ResourceManager.GetString("CreateProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once setting FPS to 120, you may won&apos;t be able to modify graphics settings in-game due to a bug.
        ///Continue? 的本地化字符串。
        /// </summary>
        internal static string FPS120Warning {
            get {
                return ResourceManager.GetString("FPS120Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not get gacha link. Please enter gacha detail page and retry. 的本地化字符串。
        /// </summary>
        internal static string GetGachaLinkFailed {
            get {
                return ResourceManager.GetString("GetGachaLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not get game directory. 的本地化字符串。
        /// </summary>
        internal static string GetGameDirectoryFailed {
            get {
                return ResourceManager.GetString("GetGameDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [×] Gacha link is invalid. Please enter gacha detail page and retry. 的本地化字符串。
        /// </summary>
        internal static string InvalidGachaLink {
            get {
                return ResourceManager.GetString("InvalidGachaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find path: {0}. 的本地化字符串。
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process exited with {0}. 的本地化字符串。
        /// </summary>
        internal static string ProcessExitedWithNonzero {
            get {
                return ResourceManager.GetString("ProcessExitedWithNonzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find registry path: {0}. 的本地化字符串。
        /// </summary>
        internal static string RegistryPathNotFound {
            get {
                return ResourceManager.GetString("RegistryPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save successfully. 的本地化字符串。
        /// </summary>
        internal static string SaveGraphicsSettingsSuccessfully {
            get {
                return ResourceManager.GetString("SaveGraphicsSettingsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [√] Gacha link is valid. 的本地化字符串。
        /// </summary>
        internal static string ValidGachaLink {
            get {
                return ResourceManager.GetString("ValidGachaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
